version: '3.8'

services:
  api:
    build:
      context: .
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
      - 5005:5005
    env_file:
      .env
    volumes:
      - ./:/app:cached

  db:
    image: postgres:13
    restart: always
    ports:
      - 15432:5432
    env_file:
      .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
